# Generated by Django 5.2 on 2025-05-13 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_imagetype_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topMenuNameKH', models.CharField(max_length=200, null=True)),
                ('topMenuNameEN', models.CharField(max_length=200, null=True)),
                ('OrderBy', models.IntegerField(blank=True, null=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
