# Generated by Django 5.2 on 2025-05-20 02:23

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_topmenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('MenuDetailDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('MenuID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.topmenu')),
            ],
        ),
    ]
